site_name: Icare

nav:
  - Home : index.md
  - User Guide : ./user_guide/index.md
  - Dev Guide : ./dev_guide/index.md
  - Workshop Exercices: ./workshop/index.md

theme:
  name: material

plugins:
  - search

extra_css: [extra.css]

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
